const header = document.querySelector('header')
const main = document.querySelector('main')
const footer = document.querySelector('footer')
const elementImage = document.querySelector('.elements__element__image')
const elementText = document.querySelector('.elements__element__text')
const wrapper = document.querySelector('.wrapper')
const footerInfo = document.querySelector('.footer__info')
const footerRight = document.querySelector('.footer__rights')
